# General Settings.
sampling_frequency: 0.5 # [Hz]

# KML layout
kml_file_prefix_name: "Piksi"
document_name: "PiksiRtkKml"
placemarker_prefix_name: "WP"

# Use optional messages/fields
use_altitude_from_enu: True # Place 'Point' at the altitude specified in 'enu_point' topic
extrude_point: True #  Connect the point to the ground with a line, only if use_altitude_from_enu is True
use_heading: True  # If true, heading is added to 'Point' description
